/**
 * This class is generated by jOOQ
 */
package jooq.classesgeradas;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>masterchico</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<jooq.classesgeradas.tables.records.ProdutoRecord, java.lang.Long> IDENTITY_PRODUTO = Identities0.IDENTITY_PRODUTO;
	public static final org.jooq.Identity<jooq.classesgeradas.tables.records.TabCategoriaRecord, java.lang.Long> IDENTITY_TAB_CATEGORIA = Identities0.IDENTITY_TAB_CATEGORIA;
	public static final org.jooq.Identity<jooq.classesgeradas.tables.records.TabFornecedorRecord, java.lang.Long> IDENTITY_TAB_FORNECEDOR = Identities0.IDENTITY_TAB_FORNECEDOR;
	public static final org.jooq.Identity<jooq.classesgeradas.tables.records.TabMercaderiaRecord, java.lang.Long> IDENTITY_TAB_MERCADERIA = Identities0.IDENTITY_TAB_MERCADERIA;
	public static final org.jooq.Identity<jooq.classesgeradas.tables.records.TabPedidoRecord, java.lang.Long> IDENTITY_TAB_PEDIDO = Identities0.IDENTITY_TAB_PEDIDO;
	public static final org.jooq.Identity<jooq.classesgeradas.tables.records.TabPedidoItemRecord, java.lang.Long> IDENTITY_TAB_PEDIDO_ITEM = Identities0.IDENTITY_TAB_PEDIDO_ITEM;
	public static final org.jooq.Identity<jooq.classesgeradas.tables.records.TabUnidadeRecord, java.lang.Long> IDENTITY_TAB_UNIDADE = Identities0.IDENTITY_TAB_UNIDADE;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<jooq.classesgeradas.tables.records.ProdutoRecord> KEY_PRODUTO_PRIMARY = UniqueKeys0.KEY_PRODUTO_PRIMARY;
	public static final org.jooq.UniqueKey<jooq.classesgeradas.tables.records.TabCategoriaRecord> KEY_TAB_CATEGORIA_PRIMARY = UniqueKeys0.KEY_TAB_CATEGORIA_PRIMARY;
	public static final org.jooq.UniqueKey<jooq.classesgeradas.tables.records.TabFornecedorRecord> KEY_TAB_FORNECEDOR_PRIMARY = UniqueKeys0.KEY_TAB_FORNECEDOR_PRIMARY;
	public static final org.jooq.UniqueKey<jooq.classesgeradas.tables.records.TabMercaderiaRecord> KEY_TAB_MERCADERIA_PRIMARY = UniqueKeys0.KEY_TAB_MERCADERIA_PRIMARY;
	public static final org.jooq.UniqueKey<jooq.classesgeradas.tables.records.TabPedidoRecord> KEY_TAB_PEDIDO_PRIMARY = UniqueKeys0.KEY_TAB_PEDIDO_PRIMARY;
	public static final org.jooq.UniqueKey<jooq.classesgeradas.tables.records.TabPedidoItemRecord> KEY_TAB_PEDIDO_ITEM_PRIMARY = UniqueKeys0.KEY_TAB_PEDIDO_ITEM_PRIMARY;
	public static final org.jooq.UniqueKey<jooq.classesgeradas.tables.records.TabUnidadeRecord> KEY_TAB_UNIDADE_PRIMARY = UniqueKeys0.KEY_TAB_UNIDADE_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<jooq.classesgeradas.tables.records.TabMercaderiaRecord, jooq.classesgeradas.tables.records.TabCategoriaRecord> FKCFCF371B8DC5035 = ForeignKeys0.FKCFCF371B8DC5035;
	public static final org.jooq.ForeignKey<jooq.classesgeradas.tables.records.TabMercaderiaRecord, jooq.classesgeradas.tables.records.TabUnidadeRecord> FKCFCF371B430BB515 = ForeignKeys0.FKCFCF371B430BB515;
	public static final org.jooq.ForeignKey<jooq.classesgeradas.tables.records.TabPedidoRecord, jooq.classesgeradas.tables.records.TabFornecedorRecord> FK9B5932FF90E579F = ForeignKeys0.FK9B5932FF90E579F;
	public static final org.jooq.ForeignKey<jooq.classesgeradas.tables.records.TabPedidoItemRecord, jooq.classesgeradas.tables.records.TabMercaderiaRecord> FKED6E4623778E541F = ForeignKeys0.FKED6E4623778E541F;
	public static final org.jooq.ForeignKey<jooq.classesgeradas.tables.records.TabPedidoItemRecord, jooq.classesgeradas.tables.records.TabPedidoRecord> FKED6E4623E0B4D61F = ForeignKeys0.FKED6E4623E0B4D61F;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<jooq.classesgeradas.tables.records.ProdutoRecord, java.lang.Long> IDENTITY_PRODUTO = createIdentity(jooq.classesgeradas.tables.Produto.PRODUTO, jooq.classesgeradas.tables.Produto.PRODUTO.ID);
		public static org.jooq.Identity<jooq.classesgeradas.tables.records.TabCategoriaRecord, java.lang.Long> IDENTITY_TAB_CATEGORIA = createIdentity(jooq.classesgeradas.tables.TabCategoria.TAB_CATEGORIA, jooq.classesgeradas.tables.TabCategoria.TAB_CATEGORIA.ID);
		public static org.jooq.Identity<jooq.classesgeradas.tables.records.TabFornecedorRecord, java.lang.Long> IDENTITY_TAB_FORNECEDOR = createIdentity(jooq.classesgeradas.tables.TabFornecedor.TAB_FORNECEDOR, jooq.classesgeradas.tables.TabFornecedor.TAB_FORNECEDOR.ID);
		public static org.jooq.Identity<jooq.classesgeradas.tables.records.TabMercaderiaRecord, java.lang.Long> IDENTITY_TAB_MERCADERIA = createIdentity(jooq.classesgeradas.tables.TabMercaderia.TAB_MERCADERIA, jooq.classesgeradas.tables.TabMercaderia.TAB_MERCADERIA.ID);
		public static org.jooq.Identity<jooq.classesgeradas.tables.records.TabPedidoRecord, java.lang.Long> IDENTITY_TAB_PEDIDO = createIdentity(jooq.classesgeradas.tables.TabPedido.TAB_PEDIDO, jooq.classesgeradas.tables.TabPedido.TAB_PEDIDO.ID);
		public static org.jooq.Identity<jooq.classesgeradas.tables.records.TabPedidoItemRecord, java.lang.Long> IDENTITY_TAB_PEDIDO_ITEM = createIdentity(jooq.classesgeradas.tables.TabPedidoItem.TAB_PEDIDO_ITEM, jooq.classesgeradas.tables.TabPedidoItem.TAB_PEDIDO_ITEM.ID);
		public static org.jooq.Identity<jooq.classesgeradas.tables.records.TabUnidadeRecord, java.lang.Long> IDENTITY_TAB_UNIDADE = createIdentity(jooq.classesgeradas.tables.TabUnidade.TAB_UNIDADE, jooq.classesgeradas.tables.TabUnidade.TAB_UNIDADE.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<jooq.classesgeradas.tables.records.ProdutoRecord> KEY_PRODUTO_PRIMARY = createUniqueKey(jooq.classesgeradas.tables.Produto.PRODUTO, jooq.classesgeradas.tables.Produto.PRODUTO.ID);
		public static final org.jooq.UniqueKey<jooq.classesgeradas.tables.records.TabCategoriaRecord> KEY_TAB_CATEGORIA_PRIMARY = createUniqueKey(jooq.classesgeradas.tables.TabCategoria.TAB_CATEGORIA, jooq.classesgeradas.tables.TabCategoria.TAB_CATEGORIA.ID);
		public static final org.jooq.UniqueKey<jooq.classesgeradas.tables.records.TabFornecedorRecord> KEY_TAB_FORNECEDOR_PRIMARY = createUniqueKey(jooq.classesgeradas.tables.TabFornecedor.TAB_FORNECEDOR, jooq.classesgeradas.tables.TabFornecedor.TAB_FORNECEDOR.ID);
		public static final org.jooq.UniqueKey<jooq.classesgeradas.tables.records.TabMercaderiaRecord> KEY_TAB_MERCADERIA_PRIMARY = createUniqueKey(jooq.classesgeradas.tables.TabMercaderia.TAB_MERCADERIA, jooq.classesgeradas.tables.TabMercaderia.TAB_MERCADERIA.ID);
		public static final org.jooq.UniqueKey<jooq.classesgeradas.tables.records.TabPedidoRecord> KEY_TAB_PEDIDO_PRIMARY = createUniqueKey(jooq.classesgeradas.tables.TabPedido.TAB_PEDIDO, jooq.classesgeradas.tables.TabPedido.TAB_PEDIDO.ID);
		public static final org.jooq.UniqueKey<jooq.classesgeradas.tables.records.TabPedidoItemRecord> KEY_TAB_PEDIDO_ITEM_PRIMARY = createUniqueKey(jooq.classesgeradas.tables.TabPedidoItem.TAB_PEDIDO_ITEM, jooq.classesgeradas.tables.TabPedidoItem.TAB_PEDIDO_ITEM.ID);
		public static final org.jooq.UniqueKey<jooq.classesgeradas.tables.records.TabUnidadeRecord> KEY_TAB_UNIDADE_PRIMARY = createUniqueKey(jooq.classesgeradas.tables.TabUnidade.TAB_UNIDADE, jooq.classesgeradas.tables.TabUnidade.TAB_UNIDADE.ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<jooq.classesgeradas.tables.records.TabMercaderiaRecord, jooq.classesgeradas.tables.records.TabCategoriaRecord> FKCFCF371B8DC5035 = createForeignKey(jooq.classesgeradas.Keys.KEY_TAB_CATEGORIA_PRIMARY, jooq.classesgeradas.tables.TabMercaderia.TAB_MERCADERIA, jooq.classesgeradas.tables.TabMercaderia.TAB_MERCADERIA.CATEGORIA_ID);
		public static final org.jooq.ForeignKey<jooq.classesgeradas.tables.records.TabMercaderiaRecord, jooq.classesgeradas.tables.records.TabUnidadeRecord> FKCFCF371B430BB515 = createForeignKey(jooq.classesgeradas.Keys.KEY_TAB_UNIDADE_PRIMARY, jooq.classesgeradas.tables.TabMercaderia.TAB_MERCADERIA, jooq.classesgeradas.tables.TabMercaderia.TAB_MERCADERIA.UNIDADE_ID);
		public static final org.jooq.ForeignKey<jooq.classesgeradas.tables.records.TabPedidoRecord, jooq.classesgeradas.tables.records.TabFornecedorRecord> FK9B5932FF90E579F = createForeignKey(jooq.classesgeradas.Keys.KEY_TAB_FORNECEDOR_PRIMARY, jooq.classesgeradas.tables.TabPedido.TAB_PEDIDO, jooq.classesgeradas.tables.TabPedido.TAB_PEDIDO.FORNECEDOR_ID);
		public static final org.jooq.ForeignKey<jooq.classesgeradas.tables.records.TabPedidoItemRecord, jooq.classesgeradas.tables.records.TabMercaderiaRecord> FKED6E4623778E541F = createForeignKey(jooq.classesgeradas.Keys.KEY_TAB_MERCADERIA_PRIMARY, jooq.classesgeradas.tables.TabPedidoItem.TAB_PEDIDO_ITEM, jooq.classesgeradas.tables.TabPedidoItem.TAB_PEDIDO_ITEM.MERCADERIA_ID);
		public static final org.jooq.ForeignKey<jooq.classesgeradas.tables.records.TabPedidoItemRecord, jooq.classesgeradas.tables.records.TabPedidoRecord> FKED6E4623E0B4D61F = createForeignKey(jooq.classesgeradas.Keys.KEY_TAB_PEDIDO_PRIMARY, jooq.classesgeradas.tables.TabPedidoItem.TAB_PEDIDO_ITEM, jooq.classesgeradas.tables.TabPedidoItem.TAB_PEDIDO_ITEM.PEDIDO_ID);
	}
}
