/**
 * This class is generated by jOOQ
 */
package jooq.classesgeradas;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Masterchico extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1309807890;

	/**
	 * The singleton instance of <code>masterchico</code>
	 */
	public static final Masterchico MASTERCHICO = new Masterchico();

	/**
	 * No further instances allowed
	 */
	private Masterchico() {
		super("masterchico");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			jooq.classesgeradas.tables.Produto.PRODUTO,
			jooq.classesgeradas.tables.TabCategoria.TAB_CATEGORIA,
			jooq.classesgeradas.tables.TabFornecedor.TAB_FORNECEDOR,
			jooq.classesgeradas.tables.TabMercaderia.TAB_MERCADERIA,
			jooq.classesgeradas.tables.TabPedido.TAB_PEDIDO,
			jooq.classesgeradas.tables.TabPedidoItem.TAB_PEDIDO_ITEM,
			jooq.classesgeradas.tables.TabUnidade.TAB_UNIDADE);
	}
}
