/**
 * This class is generated by jOOQ
 */
package jooq.classesgeradas;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in masterchico
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table masterchico.produto
	 */
	public static final jooq.classesgeradas.tables.Produto PRODUTO = jooq.classesgeradas.tables.Produto.PRODUTO;

	/**
	 * The table masterchico.tab_categoria
	 */
	public static final jooq.classesgeradas.tables.TabCategoria TAB_CATEGORIA = jooq.classesgeradas.tables.TabCategoria.TAB_CATEGORIA;

	/**
	 * The table masterchico.tab_fornecedor
	 */
	public static final jooq.classesgeradas.tables.TabFornecedor TAB_FORNECEDOR = jooq.classesgeradas.tables.TabFornecedor.TAB_FORNECEDOR;

	/**
	 * The table masterchico.tab_mercaderia
	 */
	public static final jooq.classesgeradas.tables.TabMercaderia TAB_MERCADERIA = jooq.classesgeradas.tables.TabMercaderia.TAB_MERCADERIA;

	/**
	 * The table masterchico.tab_pedido
	 */
	public static final jooq.classesgeradas.tables.TabPedido TAB_PEDIDO = jooq.classesgeradas.tables.TabPedido.TAB_PEDIDO;

	/**
	 * The table masterchico.tab_pedido_item
	 */
	public static final jooq.classesgeradas.tables.TabPedidoItem TAB_PEDIDO_ITEM = jooq.classesgeradas.tables.TabPedidoItem.TAB_PEDIDO_ITEM;

	/**
	 * The table masterchico.tab_unidade
	 */
	public static final jooq.classesgeradas.tables.TabUnidade TAB_UNIDADE = jooq.classesgeradas.tables.TabUnidade.TAB_UNIDADE;
}
