/**
 * This class is generated by jOOQ
 */
package jooq.classesgeradas.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabUnidade extends org.jooq.impl.TableImpl<jooq.classesgeradas.tables.records.TabUnidadeRecord> {

	private static final long serialVersionUID = -205514964;

	/**
	 * The singleton instance of <code>masterchico.tab_unidade</code>
	 */
	public static final jooq.classesgeradas.tables.TabUnidade TAB_UNIDADE = new jooq.classesgeradas.tables.TabUnidade();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<jooq.classesgeradas.tables.records.TabUnidadeRecord> getRecordType() {
		return jooq.classesgeradas.tables.records.TabUnidadeRecord.class;
	}

	/**
	 * The column <code>masterchico.tab_unidade.id</code>. 
	 */
	public final org.jooq.TableField<jooq.classesgeradas.tables.records.TabUnidadeRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>masterchico.tab_unidade.descricao</code>. 
	 */
	public final org.jooq.TableField<jooq.classesgeradas.tables.records.TabUnidadeRecord, java.lang.String> DESCRICAO = createField("descricao", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>masterchico.tab_unidade</code> table reference
	 */
	public TabUnidade() {
		super("tab_unidade", jooq.classesgeradas.Masterchico.MASTERCHICO);
	}

	/**
	 * Create an aliased <code>masterchico.tab_unidade</code> table reference
	 */
	public TabUnidade(java.lang.String alias) {
		super(alias, jooq.classesgeradas.Masterchico.MASTERCHICO, jooq.classesgeradas.tables.TabUnidade.TAB_UNIDADE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<jooq.classesgeradas.tables.records.TabUnidadeRecord, java.lang.Long> getIdentity() {
		return jooq.classesgeradas.Keys.IDENTITY_TAB_UNIDADE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<jooq.classesgeradas.tables.records.TabUnidadeRecord> getPrimaryKey() {
		return jooq.classesgeradas.Keys.KEY_TAB_UNIDADE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<jooq.classesgeradas.tables.records.TabUnidadeRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<jooq.classesgeradas.tables.records.TabUnidadeRecord>>asList(jooq.classesgeradas.Keys.KEY_TAB_UNIDADE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public jooq.classesgeradas.tables.TabUnidade as(java.lang.String alias) {
		return new jooq.classesgeradas.tables.TabUnidade(alias);
	}
}
