/**
 * This class is generated by jOOQ
 */
package jooq.classesgeradas.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabCategoriaRecord extends org.jooq.impl.UpdatableRecordImpl<jooq.classesgeradas.tables.records.TabCategoriaRecord> implements org.jooq.Record2<java.lang.Long, java.lang.String> {

	private static final long serialVersionUID = 761652282;

	/**
	 * Setter for <code>masterchico.tab_categoria.id</code>. 
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>masterchico.tab_categoria.id</code>. 
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>masterchico.tab_categoria.descricao</code>. 
	 */
	public void setDescricao(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>masterchico.tab_categoria.descricao</code>. 
	 */
	public java.lang.String getDescricao() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return jooq.classesgeradas.tables.TabCategoria.TAB_CATEGORIA.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return jooq.classesgeradas.tables.TabCategoria.TAB_CATEGORIA.DESCRICAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDescricao();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TabCategoriaRecord
	 */
	public TabCategoriaRecord() {
		super(jooq.classesgeradas.tables.TabCategoria.TAB_CATEGORIA);
	}

	/**
	 * Create a detached, initialised TabCategoriaRecord
	 */
	public TabCategoriaRecord(java.lang.Long id, java.lang.String descricao) {
		super(jooq.classesgeradas.tables.TabCategoria.TAB_CATEGORIA);

		setValue(0, id);
		setValue(1, descricao);
	}
}
