/**
 * This class is generated by jOOQ
 */
package jooq.classesgeradas.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProdutoRecord extends org.jooq.impl.UpdatableRecordImpl<jooq.classesgeradas.tables.records.ProdutoRecord> implements org.jooq.Record3<java.lang.Long, java.lang.String, java.lang.Double> {

	private static final long serialVersionUID = 169665945;

	/**
	 * Setter for <code>masterchico.produto.id</code>. 
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>masterchico.produto.id</code>. 
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>masterchico.produto.nome</code>. 
	 */
	public void setNome(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>masterchico.produto.nome</code>. 
	 */
	public java.lang.String getNome() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>masterchico.produto.preco</code>. 
	 */
	public void setPreco(java.lang.Double value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>masterchico.produto.preco</code>. 
	 */
	public java.lang.Double getPreco() {
		return (java.lang.Double) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.Double> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.Double> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return jooq.classesgeradas.tables.Produto.PRODUTO.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return jooq.classesgeradas.tables.Produto.PRODUTO.NOME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field3() {
		return jooq.classesgeradas.tables.Produto.PRODUTO.PRECO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getNome();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value3() {
		return getPreco();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ProdutoRecord
	 */
	public ProdutoRecord() {
		super(jooq.classesgeradas.tables.Produto.PRODUTO);
	}

	/**
	 * Create a detached, initialised ProdutoRecord
	 */
	public ProdutoRecord(java.lang.Long id, java.lang.String nome, java.lang.Double preco) {
		super(jooq.classesgeradas.tables.Produto.PRODUTO);

		setValue(0, id);
		setValue(1, nome);
		setValue(2, preco);
	}
}
