/**
 * This class is generated by jOOQ
 */
package jooq.classesgeradas.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabPedido extends org.jooq.impl.TableImpl<jooq.classesgeradas.tables.records.TabPedidoRecord> {

	private static final long serialVersionUID = 1722726563;

	/**
	 * The singleton instance of <code>masterchico.tab_pedido</code>
	 */
	public static final jooq.classesgeradas.tables.TabPedido TAB_PEDIDO = new jooq.classesgeradas.tables.TabPedido();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<jooq.classesgeradas.tables.records.TabPedidoRecord> getRecordType() {
		return jooq.classesgeradas.tables.records.TabPedidoRecord.class;
	}

	/**
	 * The column <code>masterchico.tab_pedido.id</code>. 
	 */
	public final org.jooq.TableField<jooq.classesgeradas.tables.records.TabPedidoRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>masterchico.tab_pedido.data</code>. 
	 */
	public final org.jooq.TableField<jooq.classesgeradas.tables.records.TabPedidoRecord, java.sql.Timestamp> DATA = createField("data", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>masterchico.tab_pedido.situacao</code>. 
	 */
	public final org.jooq.TableField<jooq.classesgeradas.tables.records.TabPedidoRecord, java.lang.String> SITUACAO = createField("situacao", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>masterchico.tab_pedido.fornecedor_id</code>. 
	 */
	public final org.jooq.TableField<jooq.classesgeradas.tables.records.TabPedidoRecord, java.lang.Long> FORNECEDOR_ID = createField("fornecedor_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * Create a <code>masterchico.tab_pedido</code> table reference
	 */
	public TabPedido() {
		super("tab_pedido", jooq.classesgeradas.Masterchico.MASTERCHICO);
	}

	/**
	 * Create an aliased <code>masterchico.tab_pedido</code> table reference
	 */
	public TabPedido(java.lang.String alias) {
		super(alias, jooq.classesgeradas.Masterchico.MASTERCHICO, jooq.classesgeradas.tables.TabPedido.TAB_PEDIDO);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<jooq.classesgeradas.tables.records.TabPedidoRecord, java.lang.Long> getIdentity() {
		return jooq.classesgeradas.Keys.IDENTITY_TAB_PEDIDO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<jooq.classesgeradas.tables.records.TabPedidoRecord> getPrimaryKey() {
		return jooq.classesgeradas.Keys.KEY_TAB_PEDIDO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<jooq.classesgeradas.tables.records.TabPedidoRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<jooq.classesgeradas.tables.records.TabPedidoRecord>>asList(jooq.classesgeradas.Keys.KEY_TAB_PEDIDO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<jooq.classesgeradas.tables.records.TabPedidoRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<jooq.classesgeradas.tables.records.TabPedidoRecord, ?>>asList(jooq.classesgeradas.Keys.FK9B5932FF90E579F);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public jooq.classesgeradas.tables.TabPedido as(java.lang.String alias) {
		return new jooq.classesgeradas.tables.TabPedido(alias);
	}
}
