/**
 * This class is generated by jOOQ
 */
package jooq.classesgeradas.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabFornecedor extends org.jooq.impl.TableImpl<jooq.classesgeradas.tables.records.TabFornecedorRecord> {

	private static final long serialVersionUID = 1867095594;

	/**
	 * The singleton instance of <code>masterchico.tab_fornecedor</code>
	 */
	public static final jooq.classesgeradas.tables.TabFornecedor TAB_FORNECEDOR = new jooq.classesgeradas.tables.TabFornecedor();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<jooq.classesgeradas.tables.records.TabFornecedorRecord> getRecordType() {
		return jooq.classesgeradas.tables.records.TabFornecedorRecord.class;
	}

	/**
	 * The column <code>masterchico.tab_fornecedor.id</code>. 
	 */
	public final org.jooq.TableField<jooq.classesgeradas.tables.records.TabFornecedorRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>masterchico.tab_fornecedor.fone</code>. 
	 */
	public final org.jooq.TableField<jooq.classesgeradas.tables.records.TabFornecedorRecord, java.lang.String> FONE = createField("fone", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>masterchico.tab_fornecedor.nome</code>. 
	 */
	public final org.jooq.TableField<jooq.classesgeradas.tables.records.TabFornecedorRecord, java.lang.String> NOME = createField("nome", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>masterchico.tab_fornecedor</code> table reference
	 */
	public TabFornecedor() {
		super("tab_fornecedor", jooq.classesgeradas.Masterchico.MASTERCHICO);
	}

	/**
	 * Create an aliased <code>masterchico.tab_fornecedor</code> table reference
	 */
	public TabFornecedor(java.lang.String alias) {
		super(alias, jooq.classesgeradas.Masterchico.MASTERCHICO, jooq.classesgeradas.tables.TabFornecedor.TAB_FORNECEDOR);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<jooq.classesgeradas.tables.records.TabFornecedorRecord, java.lang.Long> getIdentity() {
		return jooq.classesgeradas.Keys.IDENTITY_TAB_FORNECEDOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<jooq.classesgeradas.tables.records.TabFornecedorRecord> getPrimaryKey() {
		return jooq.classesgeradas.Keys.KEY_TAB_FORNECEDOR_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<jooq.classesgeradas.tables.records.TabFornecedorRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<jooq.classesgeradas.tables.records.TabFornecedorRecord>>asList(jooq.classesgeradas.Keys.KEY_TAB_FORNECEDOR_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public jooq.classesgeradas.tables.TabFornecedor as(java.lang.String alias) {
		return new jooq.classesgeradas.tables.TabFornecedor(alias);
	}
}
