/**
 * This class is generated by jOOQ
 */
package jooq.classesgeradas.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabPedidoItem extends org.jooq.impl.TableImpl<jooq.classesgeradas.tables.records.TabPedidoItemRecord> {

	private static final long serialVersionUID = 372429779;

	/**
	 * The singleton instance of <code>masterchico.tab_pedido_item</code>
	 */
	public static final jooq.classesgeradas.tables.TabPedidoItem TAB_PEDIDO_ITEM = new jooq.classesgeradas.tables.TabPedidoItem();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<jooq.classesgeradas.tables.records.TabPedidoItemRecord> getRecordType() {
		return jooq.classesgeradas.tables.records.TabPedidoItemRecord.class;
	}

	/**
	 * The column <code>masterchico.tab_pedido_item.id</code>. 
	 */
	public final org.jooq.TableField<jooq.classesgeradas.tables.records.TabPedidoItemRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>masterchico.tab_pedido_item.quantidadePedido</code>. 
	 */
	public final org.jooq.TableField<jooq.classesgeradas.tables.records.TabPedidoItemRecord, java.math.BigDecimal> QUANTIDADEPEDIDO = createField("quantidadePedido", org.jooq.impl.SQLDataType.DECIMAL.precision(19, 2), this);

	/**
	 * The column <code>masterchico.tab_pedido_item.quantidadeRecebido</code>. 
	 */
	public final org.jooq.TableField<jooq.classesgeradas.tables.records.TabPedidoItemRecord, java.math.BigDecimal> QUANTIDADERECEBIDO = createField("quantidadeRecebido", org.jooq.impl.SQLDataType.DECIMAL.precision(19, 2), this);

	/**
	 * The column <code>masterchico.tab_pedido_item.mercaderia_id</code>. 
	 */
	public final org.jooq.TableField<jooq.classesgeradas.tables.records.TabPedidoItemRecord, java.lang.Long> MERCADERIA_ID = createField("mercaderia_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>masterchico.tab_pedido_item.pedido_id</code>. 
	 */
	public final org.jooq.TableField<jooq.classesgeradas.tables.records.TabPedidoItemRecord, java.lang.Long> PEDIDO_ID = createField("pedido_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>masterchico.tab_pedido_item.quantidade_pedido</code>. 
	 */
	public final org.jooq.TableField<jooq.classesgeradas.tables.records.TabPedidoItemRecord, java.math.BigDecimal> QUANTIDADE_PEDIDO = createField("quantidade_pedido", org.jooq.impl.SQLDataType.DECIMAL.precision(19, 2), this);

	/**
	 * The column <code>masterchico.tab_pedido_item.quantidade_recebido</code>. 
	 */
	public final org.jooq.TableField<jooq.classesgeradas.tables.records.TabPedidoItemRecord, java.math.BigDecimal> QUANTIDADE_RECEBIDO = createField("quantidade_recebido", org.jooq.impl.SQLDataType.DECIMAL.precision(19, 2), this);

	/**
	 * Create a <code>masterchico.tab_pedido_item</code> table reference
	 */
	public TabPedidoItem() {
		super("tab_pedido_item", jooq.classesgeradas.Masterchico.MASTERCHICO);
	}

	/**
	 * Create an aliased <code>masterchico.tab_pedido_item</code> table reference
	 */
	public TabPedidoItem(java.lang.String alias) {
		super(alias, jooq.classesgeradas.Masterchico.MASTERCHICO, jooq.classesgeradas.tables.TabPedidoItem.TAB_PEDIDO_ITEM);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<jooq.classesgeradas.tables.records.TabPedidoItemRecord, java.lang.Long> getIdentity() {
		return jooq.classesgeradas.Keys.IDENTITY_TAB_PEDIDO_ITEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<jooq.classesgeradas.tables.records.TabPedidoItemRecord> getPrimaryKey() {
		return jooq.classesgeradas.Keys.KEY_TAB_PEDIDO_ITEM_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<jooq.classesgeradas.tables.records.TabPedidoItemRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<jooq.classesgeradas.tables.records.TabPedidoItemRecord>>asList(jooq.classesgeradas.Keys.KEY_TAB_PEDIDO_ITEM_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<jooq.classesgeradas.tables.records.TabPedidoItemRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<jooq.classesgeradas.tables.records.TabPedidoItemRecord, ?>>asList(jooq.classesgeradas.Keys.FKED6E4623778E541F, jooq.classesgeradas.Keys.FKED6E4623E0B4D61F);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public jooq.classesgeradas.tables.TabPedidoItem as(java.lang.String alias) {
		return new jooq.classesgeradas.tables.TabPedidoItem(alias);
	}
}
