/**
 * This class is generated by jOOQ
 */
package jooq.classesgeradas.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabMercaderia extends org.jooq.impl.TableImpl<jooq.classesgeradas.tables.records.TabMercaderiaRecord> {

	private static final long serialVersionUID = -1732633095;

	/**
	 * The singleton instance of <code>masterchico.tab_mercaderia</code>
	 */
	public static final jooq.classesgeradas.tables.TabMercaderia TAB_MERCADERIA = new jooq.classesgeradas.tables.TabMercaderia();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<jooq.classesgeradas.tables.records.TabMercaderiaRecord> getRecordType() {
		return jooq.classesgeradas.tables.records.TabMercaderiaRecord.class;
	}

	/**
	 * The column <code>masterchico.tab_mercaderia.id</code>. 
	 */
	public final org.jooq.TableField<jooq.classesgeradas.tables.records.TabMercaderiaRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>masterchico.tab_mercaderia.nome</code>. 
	 */
	public final org.jooq.TableField<jooq.classesgeradas.tables.records.TabMercaderiaRecord, java.lang.String> NOME = createField("nome", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>masterchico.tab_mercaderia.quantidade</code>. 
	 */
	public final org.jooq.TableField<jooq.classesgeradas.tables.records.TabMercaderiaRecord, java.math.BigDecimal> QUANTIDADE = createField("quantidade", org.jooq.impl.SQLDataType.DECIMAL.precision(19, 2), this);

	/**
	 * The column <code>masterchico.tab_mercaderia.quantidadeMinima</code>. 
	 */
	public final org.jooq.TableField<jooq.classesgeradas.tables.records.TabMercaderiaRecord, java.math.BigDecimal> QUANTIDADEMINIMA = createField("quantidadeMinima", org.jooq.impl.SQLDataType.DECIMAL.precision(19, 2), this);

	/**
	 * The column <code>masterchico.tab_mercaderia.categoria_id</code>. 
	 */
	public final org.jooq.TableField<jooq.classesgeradas.tables.records.TabMercaderiaRecord, java.lang.Long> CATEGORIA_ID = createField("categoria_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>masterchico.tab_mercaderia.unidade_id</code>. 
	 */
	public final org.jooq.TableField<jooq.classesgeradas.tables.records.TabMercaderiaRecord, java.lang.Long> UNIDADE_ID = createField("unidade_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>masterchico.tab_mercaderia.quantiade_minima</code>. 
	 */
	public final org.jooq.TableField<jooq.classesgeradas.tables.records.TabMercaderiaRecord, java.math.BigDecimal> QUANTIADE_MINIMA = createField("quantiade_minima", org.jooq.impl.SQLDataType.DECIMAL.precision(19, 2), this);

	/**
	 * The column <code>masterchico.tab_mercaderia.quantidade_minima</code>. 
	 */
	public final org.jooq.TableField<jooq.classesgeradas.tables.records.TabMercaderiaRecord, java.math.BigDecimal> QUANTIDADE_MINIMA = createField("quantidade_minima", org.jooq.impl.SQLDataType.DECIMAL.precision(19, 2), this);

	/**
	 * Create a <code>masterchico.tab_mercaderia</code> table reference
	 */
	public TabMercaderia() {
		super("tab_mercaderia", jooq.classesgeradas.Masterchico.MASTERCHICO);
	}

	/**
	 * Create an aliased <code>masterchico.tab_mercaderia</code> table reference
	 */
	public TabMercaderia(java.lang.String alias) {
		super(alias, jooq.classesgeradas.Masterchico.MASTERCHICO, jooq.classesgeradas.tables.TabMercaderia.TAB_MERCADERIA);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<jooq.classesgeradas.tables.records.TabMercaderiaRecord, java.lang.Long> getIdentity() {
		return jooq.classesgeradas.Keys.IDENTITY_TAB_MERCADERIA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<jooq.classesgeradas.tables.records.TabMercaderiaRecord> getPrimaryKey() {
		return jooq.classesgeradas.Keys.KEY_TAB_MERCADERIA_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<jooq.classesgeradas.tables.records.TabMercaderiaRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<jooq.classesgeradas.tables.records.TabMercaderiaRecord>>asList(jooq.classesgeradas.Keys.KEY_TAB_MERCADERIA_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<jooq.classesgeradas.tables.records.TabMercaderiaRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<jooq.classesgeradas.tables.records.TabMercaderiaRecord, ?>>asList(jooq.classesgeradas.Keys.FKCFCF371B8DC5035, jooq.classesgeradas.Keys.FKCFCF371B430BB515);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public jooq.classesgeradas.tables.TabMercaderia as(java.lang.String alias) {
		return new jooq.classesgeradas.tables.TabMercaderia(alias);
	}
}
