/**
 * This class is generated by jOOQ
 */
package jooq.classesgeradas.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabFornecedorRecord extends org.jooq.impl.UpdatableRecordImpl<jooq.classesgeradas.tables.records.TabFornecedorRecord> implements org.jooq.Record3<java.lang.Long, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -2017205910;

	/**
	 * Setter for <code>masterchico.tab_fornecedor.id</code>. 
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>masterchico.tab_fornecedor.id</code>. 
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>masterchico.tab_fornecedor.fone</code>. 
	 */
	public void setFone(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>masterchico.tab_fornecedor.fone</code>. 
	 */
	public java.lang.String getFone() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>masterchico.tab_fornecedor.nome</code>. 
	 */
	public void setNome(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>masterchico.tab_fornecedor.nome</code>. 
	 */
	public java.lang.String getNome() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return jooq.classesgeradas.tables.TabFornecedor.TAB_FORNECEDOR.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return jooq.classesgeradas.tables.TabFornecedor.TAB_FORNECEDOR.FONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return jooq.classesgeradas.tables.TabFornecedor.TAB_FORNECEDOR.NOME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getFone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getNome();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TabFornecedorRecord
	 */
	public TabFornecedorRecord() {
		super(jooq.classesgeradas.tables.TabFornecedor.TAB_FORNECEDOR);
	}

	/**
	 * Create a detached, initialised TabFornecedorRecord
	 */
	public TabFornecedorRecord(java.lang.Long id, java.lang.String fone, java.lang.String nome) {
		super(jooq.classesgeradas.tables.TabFornecedor.TAB_FORNECEDOR);

		setValue(0, id);
		setValue(1, fone);
		setValue(2, nome);
	}
}
