/**
 * This class is generated by jOOQ
 */
package jooq.classesgeradas.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabMercaderiaRecord extends org.jooq.impl.UpdatableRecordImpl<jooq.classesgeradas.tables.records.TabMercaderiaRecord> implements org.jooq.Record8<java.lang.Long, java.lang.String, java.math.BigDecimal, java.math.BigDecimal, java.lang.Long, java.lang.Long, java.math.BigDecimal, java.math.BigDecimal> {

	private static final long serialVersionUID = 474305991;

	/**
	 * Setter for <code>masterchico.tab_mercaderia.id</code>. 
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>masterchico.tab_mercaderia.id</code>. 
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>masterchico.tab_mercaderia.nome</code>. 
	 */
	public void setNome(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>masterchico.tab_mercaderia.nome</code>. 
	 */
	public java.lang.String getNome() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>masterchico.tab_mercaderia.quantidade</code>. 
	 */
	public void setQuantidade(java.math.BigDecimal value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>masterchico.tab_mercaderia.quantidade</code>. 
	 */
	public java.math.BigDecimal getQuantidade() {
		return (java.math.BigDecimal) getValue(2);
	}

	/**
	 * Setter for <code>masterchico.tab_mercaderia.quantidadeMinima</code>. 
	 */
	public void setQuantidademinima(java.math.BigDecimal value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>masterchico.tab_mercaderia.quantidadeMinima</code>. 
	 */
	public java.math.BigDecimal getQuantidademinima() {
		return (java.math.BigDecimal) getValue(3);
	}

	/**
	 * Setter for <code>masterchico.tab_mercaderia.categoria_id</code>. 
	 */
	public void setCategoriaId(java.lang.Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>masterchico.tab_mercaderia.categoria_id</code>. 
	 */
	public java.lang.Long getCategoriaId() {
		return (java.lang.Long) getValue(4);
	}

	/**
	 * Setter for <code>masterchico.tab_mercaderia.unidade_id</code>. 
	 */
	public void setUnidadeId(java.lang.Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>masterchico.tab_mercaderia.unidade_id</code>. 
	 */
	public java.lang.Long getUnidadeId() {
		return (java.lang.Long) getValue(5);
	}

	/**
	 * Setter for <code>masterchico.tab_mercaderia.quantiade_minima</code>. 
	 */
	public void setQuantiadeMinima(java.math.BigDecimal value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>masterchico.tab_mercaderia.quantiade_minima</code>. 
	 */
	public java.math.BigDecimal getQuantiadeMinima() {
		return (java.math.BigDecimal) getValue(6);
	}

	/**
	 * Setter for <code>masterchico.tab_mercaderia.quantidade_minima</code>. 
	 */
	public void setQuantidadeMinima(java.math.BigDecimal value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>masterchico.tab_mercaderia.quantidade_minima</code>. 
	 */
	public java.math.BigDecimal getQuantidadeMinima() {
		return (java.math.BigDecimal) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Long, java.lang.String, java.math.BigDecimal, java.math.BigDecimal, java.lang.Long, java.lang.Long, java.math.BigDecimal, java.math.BigDecimal> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Long, java.lang.String, java.math.BigDecimal, java.math.BigDecimal, java.lang.Long, java.lang.Long, java.math.BigDecimal, java.math.BigDecimal> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return jooq.classesgeradas.tables.TabMercaderia.TAB_MERCADERIA.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return jooq.classesgeradas.tables.TabMercaderia.TAB_MERCADERIA.NOME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field3() {
		return jooq.classesgeradas.tables.TabMercaderia.TAB_MERCADERIA.QUANTIDADE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field4() {
		return jooq.classesgeradas.tables.TabMercaderia.TAB_MERCADERIA.QUANTIDADEMINIMA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field5() {
		return jooq.classesgeradas.tables.TabMercaderia.TAB_MERCADERIA.CATEGORIA_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field6() {
		return jooq.classesgeradas.tables.TabMercaderia.TAB_MERCADERIA.UNIDADE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field7() {
		return jooq.classesgeradas.tables.TabMercaderia.TAB_MERCADERIA.QUANTIADE_MINIMA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field8() {
		return jooq.classesgeradas.tables.TabMercaderia.TAB_MERCADERIA.QUANTIDADE_MINIMA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getNome();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value3() {
		return getQuantidade();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value4() {
		return getQuantidademinima();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value5() {
		return getCategoriaId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value6() {
		return getUnidadeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value7() {
		return getQuantiadeMinima();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value8() {
		return getQuantidadeMinima();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TabMercaderiaRecord
	 */
	public TabMercaderiaRecord() {
		super(jooq.classesgeradas.tables.TabMercaderia.TAB_MERCADERIA);
	}

	/**
	 * Create a detached, initialised TabMercaderiaRecord
	 */
	public TabMercaderiaRecord(java.lang.Long id, java.lang.String nome, java.math.BigDecimal quantidade, java.math.BigDecimal quantidademinima, java.lang.Long categoriaId, java.lang.Long unidadeId, java.math.BigDecimal quantiadeMinima, java.math.BigDecimal quantidadeMinima) {
		super(jooq.classesgeradas.tables.TabMercaderia.TAB_MERCADERIA);

		setValue(0, id);
		setValue(1, nome);
		setValue(2, quantidade);
		setValue(3, quantidademinima);
		setValue(4, categoriaId);
		setValue(5, unidadeId);
		setValue(6, quantiadeMinima);
		setValue(7, quantidadeMinima);
	}
}
